[package]
name = "qrs"
version = "0.1.0"
authors = ["Devdutt Shenoi <devdutt@outlook.in>"]
edition = "2018"

[dependencies]
qrcode = "0.11"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]
wasm-opt = false
