name: rust-wasm

on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - name: Cache Dependencies
      uses: Swatinem/rust-cache@v1.2.0
    - name: Setup
      run: cargo install wasm-pack wasm-gc && rustup target add wasm32-unknown-unknown && rustup override set nightly
    - name: Build
      run: wasm-pack build --target web
    - name: Optimise
      run: wasm-gc pkg/qrs_bg.wasm
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages 
          FOLDER: ./
          CLEAN: true
    - name: Clear the cargo caches
      run: |
          cargo install cargo-cache --version 0.6.2 --no-default-features --features ci-autoclean
          cargo-cache
